### ISSUE TITLE
Multiline prompts duplicate when resizing pane in tmux

### ISSUE THREAD

**Issue by SuperSandro2000** [akinomyoga/ble.sh#173]
**ble version**: 0.4.0-devel3+7d05a28
**Bash version**: 5.1.8(1)-release (x86_64-pc-linux-gnu)

When I resize the the tmux pane with my mouse on the middle bar the prompts duplicate and inputs have a very high delay including <kbd>Ctrl</kbd>+<kbd>C</kbd>. When I run `ble-detach` and `stty sane;` this no longer happens for the pane.

![image](https://user-images.githubusercontent.com/7258858/151974046-b3325c22-3952-41e6-88d5-8d97f0bfda28.png)

**Comment by akinomyoga** [comment]
This is actually a duplicate of #142 #154, #168. This is somewhat an intended behavior. If you would like the behavior the same as Readline, you can use the following setting:

```bash
# blerc
bleopt canvas_winch_action=redraw-prev
```

The reasoning for the default behavior is explained at https://github.com/akinomyoga/ble.sh/issues/142#issuecomment-950036015. This is related to the general problem of terminal text reflowing. There is a nice summary of the problem in [README of powerlevel10k](https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window).

**Comment by akinomyoga** [comment]
> inputs have a very high delay including <kbd>Ctrl+C</kbd>.

Does this delay continue even after a long time since the pane resizing? If so, maybe there is another separate problem here besides the text reflowing issue.

**Comment by SuperSandro2000** [comment]
> Does this delay continue even after a long time since the pane resizing?

The upper pane is responsive after ~10 seconds. The lower one takes about a minute but then it works again.

**Comment by akinomyoga** [comment]
Thanks. Hmm, I cannot reproduce the phenomena in my environment.

**Q1**: Could you tell what will be shown these 10 seconds and a minute after resizing with the following setting?

```bash
$ trap 'echo WINCH$((count++)) >/dev/tty' WINCH
```

I'd like to identify whether the delay is caused by some interactions between WINCH and ble.sh or some internal processing in ble.sh. Is anything output while these high-delay time duration with this setting?

**Q2**: Does this delay also happens with `bleopt canvas_winch_action=redraw-prev`? I'd like to know these two problems are correlated or independent.

**Comment by akinomyoga** [comment]
OK. I could reproduce it.

**Comment by akinomyoga** [comment]
Strange, ... I cannot reproduce it anymore. The probability seems to be very low in my environment. @SuperSandro2000 Does it always happens in your environment? What is your outer terminal?

**Comment by SuperSandro2000** [comment]
Now I also have problems to reproduce it. I think it only happens when you didn't input anything before in the terminal. After pasting the trap it never happens or when I add it to my startup scripts. The only thing I noticed is that WHICHxx is always printed before the mini delay and the PROMPT repaints.

> Does this delay also happens with bleopt canvas_winch_action=redraw-prev? I'd like to know these two problems are correlated or independent.

It happens independent of this setting.

> Does it always happen in your environment?

It happens for me all the time when I resize a pane right after creating it without the WHINCH trap. Could it be something how I load blesh through PROMPT_COMMAND?

> What is your outer terminal?

Windows Terminal dev

**Comment by akinomyoga** [comment]
I think I have identified the partial cause. This is caused by this line in a recent commit [`e85f52cb`](https://github.com/akinomyoga/ble.sh/commit/e85f52cb1b4d21fbf0e56f133f5eeecf8e1def9b#diff-ecc73f05e37655a3123899b333e444b90cce872f8e8fa7c1a0c7d345df279f25R2106) for bash-preexec integration.

I just intended to restore the value of the shell special variable `$_` before the signal handler, but the restoring code itself is executed by `eval` command so that `$_` actually became the resoring code. Then `$_` becomes roughly 4x longer every time a signal handler is called in a row, i.e., `$_` grows exponentially until non-signal handler is called.

```
# 1st call
ble/util/setexit 1 ''
# 2nd call
ble/util/setexit 1 'ble/util/setexit 1 '\'''\'''
# 3rd call
ble/util/setexit 1 'ble/util/setexit 1 '\''ble/util/setexit 1 '\''\'\'''\'''\''\'\'''\'''\'''
# ...
```

But this doesn't explain the following behavior, which I couldn't reproduce so far in my environment.

> The only thing I noticed is that WHICHxx is always printed before the mini delay and the PROMPT repaints.

**Comment by SuperSandro2000** [comment]
> The only thing I noticed is that WHICHxx is always printed before the mini delay and the PROMPT repaints.

It could also be something different in my environment. I think if you are fast enough you can type almost immediately while the resizing still happens. While testing I dead locked my tmux and it was pinned at 100% CPU. I am not sure if this is related since I had that issue also months ago already but it didn't happen for a long time.

I also noticed something weird: when I move the pain multiple WHICH can be triggered. When I keep holding the handle and then move it again another WHICH is triggered. If you are not continuously moving it you can easily trigger 10 or more if you are unsure how big you want your pane to be.

**Comment by akinomyoga** [comment]
I have fixed it in dfc6221.

> Windows Terminal dev

I have tried Windows Terminal and noticed that it tries to render every cursor movement while rendering, so I just decided to hide the cursor while rendering in e332dc5. Although the cursor still looks frequently blinking unnecessarily while typing in Windows Terminal, I think it is better than before.

I also noticed another glitch in Windows Terminal, but will later look at it.

> The only thing I noticed is that WHICHxx is always printed before the mini delay and the PROMPT repaints.

I cannot still reproduce this behavior even with Windows Terminal (but not dev version), but maybe I misunderstand what you meant by "always printed before the mini delay". I thought you meant that `WINCHxx` is shown for every keystroke while we experience the high CPU load after the pane resizing, but that contradicts with another explanation "After pasting the trap it never happens". So I guess we shouldn't experience "the mini delay" when we set up SIGWINCH? What does "the mini delay" actually mean?

**Comment by akinomyoga** [comment]
Windows Terminal has an incredible bug... DL at the last line is broken. I think I knew that when it is not yet released. I don't understand why this primitive operation is kept broken for such a long time.

```bash
$ printf '\e[99M' # run this at the last line in Windows Terminal
```

**Comment by SuperSandro2000** [comment]
> I thought you meant that WINCHxx is shown for every keystroke while we experience the high CPU load after the pane resizing

It only showed for resizing. 

> What does "the mini delay" actually mean?

When I resized the pane with my mouse first the WHICHxx is printed and one or two seconds later I can only type in the pane. I am not sure from where this delay comes. It could also be my incompetence to click and switch fast enough.

**Comment by akinomyoga** [comment]
I see. Thank you for your explanation! Then, I guess the only remaining problem is that mini delay just after the resizing.

> When I resized the pane with my mouse first the WHICHxx is printed

Does it mean one WINCHxx is shown after the resizing, but after that, there is no response for one or two seconds without any outputs like WINCHxx?

**Comment by SuperSandro2000** [comment]
> Does it mean one WINCHxx is shown after the resizing, but after that, there is no response for one or two seconds without any outputs like WINCHxx?

I can most reliable reproduce it when multiple WHINCHxx are shown after rapidly resizing the pane multiple times in quick concessions. After every resize a WHINCHxx is shown and then it takes some time for the input to become responsive for any input. I think the WHINCHxx are always immediately though. I am not sure if they still appear when it is locked and it is quite hard for me to reliable reproduce that and still make exact observations.

**Comment by akinomyoga** [comment]
## Re: The mini delay after resizing

Not sure if related to the issue you are facing, but I noticed that the internal state can be broken if SIGWINCH signals arrive in the middle of the processing of ble.sh, so I have added a workaround 5065fda that the actual processing of SIGWINCH will be delayed when it's processing something. I think this change made ble.sh's processing of SIGWINCH significantly stabler by far.

## Re: Layout issue in Windows Terminal & Cygwin

This issue is what I faced in my environment. The terminal control functions IL and DL do not work correctly when the current cursor position in the terminal is at the bottom line (the last line). I've reported it to Cygwin [1], and Takashi (@tyan0) has made a patch [2] immediately (super-fast!).

- [1] [In Cygwin console (not Mintty), escape sequences DL/IL at the last line misbehave](https://cygwin.com/pipermail/cygwin/2022-February/250736.html)
- [2] [[PATCH] Cygwin: console: Fix IL/DL escape sequence on the last line.](https://cygwin.com/pipermail/cygwin-patches/2022q1/011734.html)

**Comment by SuperSandro2000** [comment]
> ## Re: The mini delay after resizing

I think that fixed it. Now resizing and quickly typing after that feels way more smoother. Thank you.

I am not actually using cygwin so I can't comment on that.

**Comment by akinomyoga** [comment]
Thank you!

> I am not actually using cygwin so I can't comment on that.

That's fine. Can I close the issue?
