### ISSUE TITLE
zoxide <Space><Tab> completion does not work with ble

### ISSUE THREAD

**Issue by tessus** [akinomyoga/ble.sh#580]
```console
$ ble summary

GNU bash, version 5.2.37(1)-release (x86_64-apple-darwin24.2.0)
ble.sh, version 0.4.0-devel4+d4c812b (noarch) [git 2.49.0, GNU Make 3.81, GNU Awk 5.3.1, API 4.0, PMA Avon 8-g1]
bash-completion, version 2.16.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
fzf key-bindings, version +93cb3758 (noarch) (integration: on)
fzf completion, version +93cb3758 (noarch) (integration: on)
starship, version 1.23.0 (rustc 1.86.0 (05f9846f8 2025-03-31),stable-x86_64-apple-darwin 2025-04-27 18:07:43 -04:00)
zoxide, version 0.9.7 (/Users/tessus/.cargo/bin/zoxide)
atuin, version 18.6.0-beta.1-7dfd777a (/Users/tessus/.cargo/bin/atuin)
locale: LANG=en_US.utf-8 LC_ALL=en_US.utf-8 LC_CTYPE=en_US.utf-8 LC_TERMINAL=iTerm2 LC_TERMINAL_VERSION=3.5.13
terminal: TERM=xterm-256color wcwidth=15.0-west/16.0-2+ri, xterm:2500 (64;2500;0)
options: +extglob -hostcomplete +inherit_errexit +login_shell
```

### Description

I have also opened this issue at zoxide, but after a bit more debugging it turned out to be related to ble. I am using zoxide 0.9.7 and it is initialized like this:

```
eval "$(zoxide init --cmd cd bash)"
```

After selecting the directory, I should automatically be changed into that dir, but this does not happen.

### `cd foo<SPACE><TAB>`

When I use `cd foo<SPACE><TAB>`, the options are shown with fzf. However, when I select one and hit enter, nothing happens.

https://github.com/user-attachments/assets/c8fbe8a9-54af-46c8-8279-2c0015ac61aa

### `cdi foo<ENTER>`

But when I do a `cdi foo<ENTER>`, fzf shows up and upon return I am changed into the selected directory.

https://github.com/user-attachments/assets/a90169b4-6587-4273-b348-f708fad6279f

### Additional info

I have 2 VMs (macOS and Linux) available. Please let me know, if you need access, in which case I'll send the connection info again by email and start the VMs.

**Comment by akinomyoga** [comment]
`ble.sh` has a dedicated completion setting for `cd` that overrides a completion setting configured by Bash's `complete`. Zoxide's completion for `cd` is provided by `complete`. To enable the completion provided through `complete`, one needs to unset the shell function `ble/cmdinfo/complete:cd` upon loading the completion module:

```bash
# ~/.blerc

ble-import -C 'unset -f ble/cmdinfo/complete:cd' core-complete
```

**Comment by tessus** [comment]
Thanks for the quick reply. Where exactly do I put this line?
Also, what happens to the other apps? Will starship and atuin still work? I suspect there was a reason why you used a dedicated completion setting for `cd`.

The structure of my `.bashrc` is as follows:

```bash
. ~/.local/share/blesh/ble.sh
eval "$(zoxide init --cmd cd bash)"
eval "$(starship init bash)"
eval "$(atuin init bash)"
```

**Comment by tessus** [comment]
I tried setting it before the zoxide eval. No change.
I also put it in `.blerc`. No change.

**Comment by akinomyoga** [comment]
> Thanks for the quick reply. Where exactly do I put this line?

Anywhere in `~/.blerc`.

----

OK, so I guess you also load the fzf-completion setting elsewhere. I could reproduce the problem when I initialize zoxide before fzf-completion is initialized (through the delayed `ble-import -d`).

Actually, the Zoxide completion also needs adjustment (`integration/zoxide`) like the fzf completion, but the adjustment for Zoxide is normally automatically loaded by detecting the Zoxide completion. However, when the fzf-completion overrides Zoxide's completion setting (`__zoxide_z_complete`) with the fzf version (`_fzf_dir_completion`), ble.sh fails to detect the Zoxide completion and the adjustment for the Zoxide completion is not automatically loaded.

The following setting should fix the problem.

```bash
# ~/.blerc

ble-import integration/zoxide
```

**Comment by tessus** [comment]
Yes, fzf integration happens here:

```
while read -r f; do . "$f"; done < <(find "$HOME/.bashrc.d/" -name "*.sh" | sort)
```

> I could reproduce the problem when I initialize zoxide before fzf-completion is initialized (through the delayed ble-import -d).

So for me this means that my fzf stuff is done before the zoxide eval. Btw, it looks like this:

```
	ble-import -d integration/fzf-completion
	ble-import integration/fzf-key-bindings
```

I've added the following to my .blerc:

```
ble-import -C 'unset -f ble/cmdinfo/complete:cd' core-complete
ble-import integration/zoxide
```

It still doesn't work. I also tried only the 2nd line in .blerc. Doesn't work either.

**Comment by akinomyoga** [comment]
Ah, sorry. Could you try the deferred loading of `integration/zoxide`? `integration/zoxide` needs to be loaded after your `eval "$(zoxide ...)"`.

```bash
ble-import -d integration/zoxide
```

----

> So for me this means that my fzf stuff is done before the zoxide eval. Btw, it looks like this:

You specify `-d` to load `integration/fzf-completion`, which means that the actual initialization is deferred until all other initialization finish. In this case, the initialization of `fzf-completion` is done after the zoxide initialziation.

**Comment by tessus** [comment]
Yes, I remember you gave me those 2 fzf import commands a while back. I couldn't really remember why the `-d`...

ok, now I have the following 2 imports at the end of my .blerc:

```
# Zoxide integration
ble-import -C 'unset -f ble/cmdinfo/complete:cd' core-complete
ble-import -d integration/zoxide
```

And.... it works. More or less:

https://github.com/user-attachments/assets/b241be5c-3af2-4040-9dc6-60f1a7e49ba4

It does not automatically switch into the directory, but I have seen other issues in the zoxide repo that describe this behavior. Although I am not sure, whether the dev has looked into this.

I have to press enter twice, but ok, better than not working at all.

Will those 2 lines in my .blerc interfere with any other apps?

Btw, instead of closing this issue maybe you can move it to the discussions. This info could be helpful to others as well.

**Comment by tessus** [comment]
Hmm, I looked at the zoxide repo and there is a commit in master that makes the situation worse. I am afraid I won't be able to use the `<Space><Tab>` completion at all (when a new version is released) and will have to use `cdi` instead.

Unfortunately I am not too familiar with this area of bash (completion and prompt rewrite) and thus I can't figure out what's wrong and fix it.

**Comment by akinomyoga** [comment]
> And.... it works. More or less:
> 
>  zoxide4.mp4 
>
> It does not automatically switch into the directory,

In my environment, even without `ble.sh`, <kbd>SP TAB</kbd> and selecting an item & <kbd>RET</kbd> inside fzf doesn't automatically run the command. It leaves the command `cd <prefix> z#<absolute-path>` in the command line. I used the following two-line bashrc to test that (with zoxide-0.9.4 and fzf-0.57.0):

```bash
eval "$(zoxide init --cmd cd bash)"
eval "$(fzf --bash)"
```

Was the feature of automatically changing the directory introduced in zoxide recently? Or do you have an additional setting to enable it (that works even without ble.sh)?

> but I have seen other issues in the zoxide repo that describe this behavior.

Could you point me to which issues I should look at?

> Will those 2 lines in my .blerc interfere with any other apps?

They shouldn't.

As for your initial question in https://github.com/akinomyoga/ble.sh/issues/580#issuecomment-2843800902 about removing the dedicated cd completion, the dedicated cd completion was just intended to replace `bash-completion`'s cd completion, which was poorer before. Overwriting it with another completion setting wouldn't be a problem. In particular, when the behavior of the `cd` command is replaced by an alias, the completion setting should be replaced with the specific one designed for the overriding command

Also, the dedicated `cd` completion was a test case of ble.sh's native completion setting interface. I originally intended to provide a new completion setting interface better than Bash's `complete`, but maybe I should give up an idea of completely separating the new completion interface and the conventional `complete` system because of tools like `fzf` trying to do something non-trivial on other completion settings based on `complete`.

Actually, since you already load `integration/fzf-completion`, the first line `ble-import -C 'unset -f ble/cmdinfo/complete:cd' core-complete` is unnecessary because [it is already executed in `integration/fzf-completion`](https://github.com/akinomyoga/blesh-contrib/blob/e12501e0b2993bc09495e45c39d5c4abeb8e25f7/integration/fzf-completion.bash#L20). I.e., you've already been executing that line through `integration/fzf-completion` for a long time.

As for the second line, it just adds additional processing around functions defined by Zoxide, so it shouldn't affect other applications. Of course, if an application uses the shell functions provided by Zoxide, the behavior would be affected, but even in that case, I believe `integration/zoxide` should solve the compatibility problem of the application with `ble.sh`.

> Btw, instead of closing this issue maybe you can move it to the discussions. This info could be helpful to others as well.

I'm now trying to looking into this if `ble.sh` can automatically detect and handle this.

**Comment by akinomyoga** [comment]
> Was the feature of automatically changing the directory introduced in zoxide recently? Or do you have an additional setting to enable it (that works even without ble.sh)?

According to https://github.com/ajeetdsouza/zoxide/issues/1043#issuecomment-2845804479, I think Zoxide has never provided the feature for Bash to automatically change the directory on pressing <kbd>RET</kbd> inside fzf called by <kbd>SP TAB</kbd>. It is a feature available only in Zsh and Fish and unavailable in Bash regardless of `ble.sh`.

**Comment by akinomyoga** [comment]
> P.S.: I did some more testing. The new commit in zoxide master works without ble - sort of. It still does not automtically switch into the dir, but instead of `cd foo z#/path/here/` it shows `cd '/path/here'`. I guess the integration will have to be updated, when a new zoxide release is published.

OK, I confirmed the behavior with the current `main` branch of Zoxide.

**Comment by akinomyoga** [comment]
[The new code in Zoxide](https://github.com/ajeetdsouza/zoxide/commit/6679619c00c2ca7381f2ed72b29581a2f2750f2c#diff-274b5d33f302440515611f9784f98f45c9f066e5f8e994798ed19068413e612aR160-R164) directly changes Readline's raw binding `\builtin bind`, so it replaces the core binding of `ble.sh`. It breaks not only the behavior for the completion, but arbitrary random parts of ble.sh would also be broken by directly touching `\builtin bind`). As I described in [the limitation section of `ble.sh`'s README](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#limitations-and-assumptions),

> - `ble.sh` overrides Bash's built-in commands (`trap`, `readonly`, `bind`, `history`, `read`, and `exit`) with shell functions to adjust the behavior of each built-in command and prevent them from interfering with `ble.sh`. If the user or another framework directly calls the original builtins through `\builtin BUILTIN`, or if the user or another framework replaces the shell functions, the behavior is undefined.

`ble.sh` is implemented based on `bind`, so if another framework removes `ble.sh`'s `bind` settings using `\builtin bind`, there isn't much thing that can be done on `ble.sh`'s side.

**Comment by tessus** [comment]
> Was the feature of automatically changing the directory introduced in zoxide recently? 

No, but I think to remember (and I could be wrong) that this worked in the past. 

> Or do you have an additional setting to enable it (that works even without ble.sh)?

Nope, it does not work with or without ble.

> Could you point me to which issues I should look at?

Hmm, I've been looking for a while now, but I can't find them anymore. I should have written down the issue numbers.

> I think Zoxide has never provided the feature for Bash

It's possible. In that case I remembered incorrectly. But when I tried zoxide for the first time, I checked out all the cool features and thought "Wow, that's nifty". If that didn't work, I would have opened an issue right away... 

> It breaks not only the behavior for the completion, but arbitrary random parts of ble.sh would also be broken 

This certainly sucks.

**Comment by akinomyoga** [comment]
> > Btw, instead of closing this issue maybe you can move it to the discussions. This info could be helpful to others as well.
> 
> I'm now trying to look into this if `ble.sh` can automatically detect and handle the issue.

In commit 788dfd15ca720d955215100eba6a72e88b7795f0, I implemented the detection so that you don't have to write the extra settings as in https://github.com/akinomyoga/ble.sh/issues/580#issuecomment-2843956318.

> Hmm, I looked at the zoxide repo and there is a commit in master that makes the situation worse. I am afraid I won't be able to use the `<Space><Tab>` completion at all (when a new version is released) and will have to use `cdi` instead.

I submitted a PR to the upstream: https://github.com/ajeetdsouza/zoxide/pull/1048.

**Comment by tessus** [comment]
Awesome, thank you.

**Comment by akinomyoga** [comment]
I think everything is resolved now. Can I close the issue?

**Comment by tessus** [comment]
Yes, thanks again for all the work and time that went into this.
