### ISSUE TITLE
Completions appearing with `declare -a compgen=...`

### ISSUE THREAD

**Issue by allenap** [akinomyoga/ble.sh#603]
```console
$ ble summary
GNU bash, version 5.3.0(1)-release (aarch64-apple-darwin24.4.0)
ble.sh, version 0.4.0-devel4+14f98dd8 (noarch) [git 2.50.0, GNU Make 3.81, GNU Awk 5.3.1, API 4.0, (GNU MPFR 4.2.2, GNU MP 6.3.0)]
bash-completion, version 2.16.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
atuin, version 18.6.1 (/opt/homebrew/bin/atuin)
locale: LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8
terminal: TERM=tmux-256color wcwidth=16.0-west/16.0-2+ri, tmux:0 (84;0;0)
options: -histexpand +cdspell +dirspell +extglob +globstar +histappend -hostcomplete +inherit_errexit +lithist +login_shell
```

After a reboot, shell completions have gone awry (though I doubt the reboot was the cause; more likely, restarting tmux, shells, etc.). For example:

```console
$ mkdir foo && cd foo && touch a b
$ ls
a  b
$ ls <tab>
$ ls 'declare -a compgen=([0]="a" [1]="b")'
```

i.e. hitting tab after `ls ` completes the line with `'declare -a compgen=([0]="a" [1]="b")'`.

Opening a new shell without `ble.sh` returns me to correct completion behaviour, albeit without the niceties of `ble.sh` (and Atuin).

The same happens inside or outside of `tmux`. I am using Ghostty but this also happens in WezTerm and Terminal.app.

**Comment by akinomyoga** [comment]
> In fact, I seem to have narrowed down the problem to sourcing `$(brew --prefix)/etc/profile.d/bash_completion.sh`. If I remove this line, all is well. I have `bash-completion@2` installed via Homebrew (as well as Bash 5.3).

I still cannot reproduce the problem. I also use 5.3.0 and bash-completion 2.16.0 of the exact same version, though I'm on GNU/Linux and I don't have macOS.

Does that mean the problem disappears when you use "(All your configs) minus (bash-completion)"? Could you check if the problem reproduces with "only ble.sh and bash-completion"?

**Comment by allenap** [comment]
> However, there's more to the story. I put all of my usual configuration back with one change: source `ble.sh` (and initialise Atuin) _before_ bash-completion. Now I get the above behaviour too, and:

- …
- When I start a new `tmux` session, behaviour also reverts to that which I originally reported.

**Comment by akinomyoga** [comment]
`ble.sh` uses the new `compgen` feature `compgen -V` when the Bash version is 5.3.

https://github.com/akinomyoga/ble.sh/blob/14f98dd899cd2d95bc37f09264a1b7ed0b99b901/lib/core-complete.sh#L4354-L4361

- **Q5**: Could you provide the result of the following command?

```console
$ declare -p _ble_bash
```

**Comment by akinomyoga** [comment]
- **Q6**: I'd like to get a trace log. Could you follow the following steps and attach the generated text `~/blesh.issue603.txt`?
  1. Put the following settings below `source /path/to/ble.sh ...` in `~/.bashrc`
  2. Start a new Bash session
  3. Reproduce the problem of `'declare -a compgen=(...)'` by inputting `ls <tab>`.
  4. Exit the session
  5. A file `~/blesh.issue603.txt` should be created in the home directory.

```bash
function debug/compgen.advice {
  if [[ :$comp_type: == *:auto:* ]]; then
    ble/function#advice/do
    return "$?"
  fi

  local PS4='+$BASH_SOURCE:$LINENO:$FUNCNAME: ' BASH_XTRACEFD
  exec {BASH_XTRACEFD}>> ~/blesh.issue603.txt
  {
    printf '# args:'
    printf ' %q' "${ADVICE_WORDS[@]}"
    printf '\n'
    printf '# start: %(%F %T %Z)T\n' -1
  } >&"$BASH_XTRACEFD"
  ble/debug/print-variables -t '# vars' cmd COMP{1,2,S,V} comp_type comp_{line,point,words,cword} 2>&"$BASH_XTRACEFD"
  local -
  set -x
  ble/function#advice/do
  set +x
  ble/debug/print-variables -t '# vars' cand_{word,cand,count} 2>&"$BASH_XTRACEFD"
}
ble-import -C 'ble/function#advice around ble/complete/progcomp/.compgen debug/compgen.advice' core-complete
```

- **Q7**: Could you also tried the same for `ls -<tab>` issue (which happened with `.bashrc` of only `ble.sh` and `bash-completion`)?

**Comment by allenap** [comment]
> * **Q5**: Could you provide the result of the following command?
>
> ```console 
> $ declare -p _ble_bash
> ```

```console
> $ declare -p _ble_bash
declare -- _ble_bash="50300"
```

**Comment by allenap** [comment]
> * **Q6**: I'd like to get a trace log. Could you follow the following steps and attach the generated text `~/blesh.issue603.txt`?

https://gist.github.com/allenap/878cf1178ed411d14dfe88d125b7f576

> * **Q7**: Could you also try the same for `ls -<tab>` issue (which happened with `.bashrc` of only `ble.sh` and `bash-completion`)?

https://gist.github.com/allenap/21b28e77341ce7879f61c3815148b9d5

I hope I correctly generated/captured those traces 🤞 Thank you for this 🙏

**Comment by aaronjamt** [comment]
I'm also encountering this issue, except Q2 above still reproduces it for me:
> * **Q2**: Does the problem reproduce with the following simple `~/.bashrc` with only the plain `ble.sh`?
> 
> ```
> # bashrc
> 
> HISTFILE=/dev/null # This is needed to protect your `~/.bash_history`. Otherwise it may be truncated to 500 entries
> source /path/to/ble.sh --norc
> ```

As a result, I have no aliases defined or anything like that. Everything else I have the same output for, and here are my trace files for good measure:

* **Q6**:
[blesh.issue603.txt](https://github.com/user-attachments/files/21203163/blesh.issue603.txt)

* **Q7**:
[blesh.issue603.txt](https://github.com/user-attachments/files/21203182/blesh.issue603.txt)

Both of those were captured with the following `.bashrc`:
```sh
HISTFILE=/dev/null
source ~/.local/share/blesh/ble.sh --norc

function debug/compgen.advice {
  if [[ :$comp_type: == *:auto:* ]]; then
    ble/function#advice/do
    return "$?"
  fi

  local PS4='+$BASH_SOURCE:$LINENO:$FUNCNAME: ' BASH_XTRACEFD
  exec {BASH_XTRACEFD}>> ~/blesh.issue603.txt
  {
    printf '# args:'
    printf ' %q' "${ADVICE_WORDS[@]}"
    printf '\n'
    printf '# start: %(%F %T %Z)T\n' -1
  } >&"$BASH_XTRACEFD"
  ble/debug/print-variables -t '# vars' cmd COMP{1,2,S,V} comp_type comp_{line,point,words,cword} 2>&"$BASH_XTRACEFD"
  local -
  set -x
  ble/function#advice/do
  set +x
  ble/debug/print-variables -t '# vars' cand_{word,cand,count} 2>&"$BASH_XTRACEFD"
}
ble-import -C 'ble/function#advice around ble/complete/progcomp/.compgen debug/compgen.advice' core-complete
```

**Comment by ionesculiviucristian** [comment]
Hi. I have the same issue:

```
❯ ble summary
GNU bash, version 5.3.0(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel4+14f98dd8 (noarch) [git 2.50.1, GNU Make 4.4.1, GNU Awk 5.3.2, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.2, GNU MP 6.3.0)]
bash-completion, version 2.16.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
starship, version 1.23.0+661c8a2c1 (rustc 1.86.0 (05f9846f8 2025-03-31) (Arch Linux rust 1:1.86.0-1), 2025-04-27 16:09:36 +00:00)
atuin, version 18.6.1 (/usr/bin/atuin)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-kitty wcwidth=16.0-west/16.0-2+ri, kitty:0 (1;4000;42)
options: +extglob +histappend -hostcomplete +inherit_errexit
```

**Comment by ionesculiviucristian** [comment]
If i downgrade bash the problem is gone:
```
[liviu@archlinux ~]$ bash --version
GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu)
```

**Comment by Gabryx64** [comment]
I can confirm the issues arises from the features that run when `_ble_bash` is >= 50300. I fixed this by adding `declare -- _ble_bash="50299"` to my `~/.bashrc`

**Comment by akinomyoga** [comment]
Sorry for my delayed reply. According to the provided trace logs, an AWK script used to serialize the generated completions seems to behave in an unexpected way. I'm busy now, but I'll try to find the time in a few days.

**Comment by LeonardoMor** [comment]
Might be one of those were macOS `awk` is not the same as GNU `awk`.

**Comment by akinomyoga** [comment]
The present issue is unrelated to macOS awk. Rather, the problem is caused with GNU awk, which ble.sh uses when `nawk` and `mawk` are not found (Note: macOS awk is a variant of nawk, but ble.sh avoids using it because it has strange modifications by Apple, Inc.).

**Comment by akinomyoga** [comment]
I pushed a fix for the first issue of `declare -a comgpen=(...)` (commit 2124463a0fdd0c987a8928a5c102f4aff364479b). I haven't yet investigated the second issue of inserting completion descriptions in the command line.

**Comment by w568w** [comment]
I can confirm that the issue has been fixed. 🚀

**Comment by aaronjamt** [comment]
I've also updated to commit https://github.com/akinomyoga/ble.sh/commit/2124463a0fdd0c987a8928a5c102f4aff364479b and can confirm that fixes it for me. FWIW, here's my current bash and readline versions:
```
bash 5.3.0-1
readline 8.3.0-3
```

**Comment by david** [comment]
Just an FYI, I had this same issue, which https://github.com/akinomyoga/ble.sh/commit/2124463a0fdd0c987a8928a5c102f4aff364479b fixes, but I can still reproduce it if I start Bash with `bash -l`.

**Comment by darukutsu** [comment]
Does completing aliases works for you? It stopped working for me.

For example:
```
alias SS='sudo systemctl'
complete -F _complete_alias SS
```

**Comment by aaronjamt** [comment]
> Does completing aliases (after patch) works for you? It stopped working for me.
> 
> For example:
> 
> ```
> alias SS='sudo systemctl'
> complete -F _complete_alias SS
> ```

I tried running both those and then running `SS status` and it worked fine on my machine with that patch.

**Comment by akinomyoga** [comment]
> Just an FYI, I had this same issue, which 2124463 fixes, but I can still reproduce it if I start Bash with `bash -l`.

@david Just to confirm which issue you are facing, can I think you don't have the issue of `declare -a compgen=(...)` when you start Bash without `-l`, while you have the issue of `declare -a compgen=(...)` when you start Bash with `-l`. One possibility is that you load different versions of `ble.sh` depending on the setup. What are the contents of your `~/.bash_profile` and `~/.bashrc`? How do you load `ble.sh` in each case?

**Comment by darukutsu** [comment]
Thanks for quick reply, I enabled `shopt -s progcomp_alias` and disabled my bindings. cykerway/complete-alias don't seem to intervene with this setup so I kept it in config. Now aliases complete. Apparently issue wasn't only with aliases not completing, but anything with sudo (doesn't need to be alias) completes options of sudo instead of command runned with sudo. This doesn't happen without blesh.

```
 $  sudo systemctl -A
-A                 --askpass          -a type            --auth-type=type   --background
--bell             -B                 -b                 --chdir=directory  --close-from=num
-C num             -D directory       --edit             -e                 -E
-g group           --group=group      -h                 --help             --host=host
-H                 -i                 -K                 -k                 -l
--list             --login            -n                 -N                 --non-interactive
--no-update        -P                 -p prompt          --preserve-env     --preserve-groups
--prompt=prompt    --remove-timestamp --reset-timestamp  --set-home

$  sudo ls -A
-A                : # Path to askpass helper program Path askpass /usr/X11R6/bin/ssh-askpass
--askpass         : [-A] # Path to askpass helper program Path askpass /usr/X11R6/bin/ssh-askpass
-a type           : Use the specified BSD authentication type when validating the user, if allowed by /…
--auth-type=type  : [-a] Use the specified BSD authentication type when validating the user, if allowed…
--background      : [-b] Run the given command in the background. It is not possible to use shell job c…
...
```

I haven't updated since May 4 so it isn't probably related to this issue.
I also switched to `bash-completion-git` version since update for extra has not landed yet.

**Comment by akinomyoga** [comment]
@darukutsu OK, I seem to be able to reproduce the problem, but it seems to be caused by the latest push. Commit 622cb2475ff1fe6ac04d5e71d6a8614723e953c0 seems to be affecting. However, I cannot reproduce the problem with older commits. What is the result of the following command?

```bash
$ ble summary
```

**Comment by darukutsu** [comment]
```
 $  ble summary
GNU bash, version 5.3.0(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel4+2124463a (noarch) [git 2.50.1, GNU Make 4.4.1, GNU Awk 5.3.2, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.2, GNU MP 6.3.0)]
bash-completion, version 2.16.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
atuin, version 18.7.1 (/usr/bin/atuin)
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-kitty wcwidth=16.0-west/16.0-2+ri, kitty:0 (1;4000;42)
options: -emacs +vi +extglob +histappend -hostcomplete +inherit_errexit +progcomp_alias
[ble: elapsed 79.96ms (CPU 103.6%)] ble summary
```

**Comment by akinomyoga** [comment]
> ```
> ble.sh, version 0.4.0-devel4+2124463a (noarch)
> ```

Thanks, so this is the latest version. You've actually updated ble.sh, and this is consistent with my observation. 622cb2475ff1fe6ac04d5e71d6a8614723e953c0 seems to have broken something, though I don't have an idea for now.

**Comment by akinomyoga** [comment]
@LEI Could you make an independent issue to report a new issue. Currently, in this thread, four or five issues are discussed at the same time. In addition, without creating a new issue, you are skipping the information that I request in the issue template.

**Comment by akinomyoga** [comment]
@david In case you missed the following command,

> *From https://github.com/akinomyoga/ble.sh/issues/603#issuecomment-3091247165*
>
> > Just an FYI, I had this same issue, which [2124463](https://github.com/akinomyoga/ble.sh/commit/2124463a0fdd0c987a8928a5c102f4aff364479b) fixes, but I can still reproduce it if I start Bash with `bash -l`.
> 
> [@david](https://github.com/david) Just to confirm which issue you are facing, can I think you don't have the issue of `declare -a compgen=(...)` when you start Bash without `-l`, while you have the issue of `declare -a compgen=(...)` when you start Bash with `-l`. One possibility is that you load different versions of `ble.sh` depending on the setup. What are the contents of your `~/.bash_profile` and `~/.bashrc`? How do you load `ble.sh` in each case?

**Comment by akinomyoga** [comment]
> Thanks, so this is the latest version I pushed a few days ago. You've actually updated ble.sh, and this is consistent with my observation. 622cb24 seems to have broken something, though I don't have an idea for now.

@darukutsu I fixed the problem of `sudo cmd ...` in commit edb21da9cd8fdffa575a8ff6474112aab8e8ead7.

**Comment by david** [comment]
Terribly sorry for the delayed response. It was indeed a problem with my `.bash_profile`, which was sourcing my `.bashrc`.

**Comment by akinomyoga** [comment]
Thanks!

**Comment by akinomyoga** [comment]
Although we haven't yet received any responses to https://github.com/akinomyoga/ble.sh/issues/603#issuecomment-3094505296, I think all the issues reported here have been solved now. Let's close the issue.
